version: "3.8"

services:
  backend:
    build:
      context: ./BackEnd/pogodo
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql

  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3500
    depends_on:
      - backend

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pogodo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: