version: "3.8"
services:
  backend:
    build:
      context: ./BackEnd/pogodo
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
    volumes:
      - ./BackEnd/pogodo:/BackEnd/pogodo  # Mount the correct directory
      - /BackEnd/pogodo/node_modules  # Preserve node_modules in the container

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3500
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend