version: "3.8"
services:
  backend:
    build: ./BackEnd
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
    volumes:
      - ./BackEnd:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3500
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
