services:
  backend:
    build:
      context: ./BackEnd/pogodo
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-ogo-pogo-ogo-pogo.h.aivencloud.com:16239/defaultdb
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_fr4fLxnT_9BoiTMNc-6

  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:3500
    depends_on:
      - backend