name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.1'
          distribution: 'temurin'

      - name: Set Up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build and test Spring Boot application
        run: |
          cd BackEnd/pogodo
          mvn clean install

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend  # wait for backend to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd FrontEnd
          npm install

      - name: Build frontend with Vite
        run: |
          cd FrontEnd
          npm run build


    
